### ISSUE TITLE
Invalid mount point: `/`

### ISSUE THREAD

**Issue by claymcleod** [ohsu-comp-bio/funnel#1225]
**Describe the bug**

I'm trying to run `funnel` locally (being driven by Sprocket), and I'm getting the following error from the Funnel engine.

```
docker: Error response from daemon: invalid volume specification: '/host_mnt/<path>/funnel-work-dir/<random-string>:/:rw': invalid mount config for type "bind": invalid specification: destination can't be '/'
```

**To Reproduce**

1. Download funnel and run with `funnel server run` (no arguments/options).
2. Download Sprocket ([link](https://github.com/stjude-rust-labs/sprocket/releases/tag/v0.13.0)).
3. Write a configuration for Sprocket to dispatch jobs to the Funnel server.

```toml
[backend]
type = "tes"
url = "http://localhost:8000/"
inputs = "file:///<path>/<to>/<your>/<folder>/inputs/"
outputs = "file:///<path>/<to>/<your>/<folder>/outputs/"
interval = 10
insecure = true
```
4. Write the example WDL file on the [OpenWDL quickstart guide](https://docs.openwdl.org/getting-started/quickstart.html) to `example.wdl`.
5. Try to run the WDL workflow with `sprocket run example.wdl main.name="World" --overwrite --config config.toml`

**Expected behavior**

The workflow to complete successfully.

**Screenshots**

_Not applicable._

**Environment (please complete the following information):**
 - Environment: Mac OSX 15.5
 - Version: Funnel v0.11.0

**Additional context**

_None._
