### ISSUE TITLE
storage/swift: upload fails on large objects

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#257]
Getting upload errors "Too Large Object" from swift.

Related info:
https://godoc.org/github.com/ncw/swift#Connection.DynamicLargeObjectCreate

https://github.com/ncw/rclone/commit/cc7b9af50ead0ed209afd3e70fd29975180eb8db

**Comment by adamstruck** [comment]
I was able to upload a 5 GB file without a problem using:

```YAML
{
  "name": "Large file download/upload example",
  "executors": [
    {
      "image": "biocontainers/samtools:1.3.1",
      "command": ["sh", "-c", "samtools view /tmp/inputs/NA21097.cram | head -n 100 | md5sum"],
      "stdout": "/tmp/outputs/stdout"
    }
  ],
  "inputs": [
    {
      "url": "swift://funnel-test/inputs/NA21097.mapped.ILLUMINA.bwa.GIH.low_coverage.20120522.bam.cram",
      "path": "/tmp/inputs/NA21097.cram"
    }
  ],
  "outputs": [
    {
      "url": "swift://funnel-test/outputs/NA21097.cram",
      "path": "/tmp/inputs/NA21097.cram"
    },
    {
      "url": "swift://funnel-test/outputs/NA21097_100.md5sum",
      "path": "/tmp/outputs/stdout"
    }
  ]
}
```
