### ISSUE TITLE
Local worker WorkDir config

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#30]
While running funnel in local mode, I had config including the server's WorkDir, e.g.

```
Storage:
  - Local:
      AllowedDirs:
      - /home/strucka/mc3
      - /home/ubuntu/data-mount/mc3-bunny
WorkDir: /home/ubuntu/data-mount/mc3-bunny/funnel-work
```

During debugging, I was surprised to find that the worker's files were not being written to this WorkDir path. Instead the worker config defaults to "tes-work-dir", and this doesn't get passed on to the worker (again, local mode).

Perhaps we can simplify this config and make it more obvious?
