### ISSUE TITLE
storage: google storage should be on by default

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#332]
This is the config currently required to enable google bucket storage:
```
Worker:
  Storage:
    GS:
      - FromEnv: true
```

We've discussed that storage should be on by default where possible, and we'll have an additional flag to disable it explicitly.
