### ISSUE TITLE
Configuration for replacing path prefixes

### ISSUE THREAD

**Issue by kellrott** [ohsu-comp-bio/funnel#708]
Use case: workflow engine expects files to be mounted on local file system, but worker nodes will be receiving files from object storage.

Possible solution:
1. Mount object store on head node using fuse mount, such as s3fs-fuse, to path like `/var/run/s3-bucket`
2. Configure funnel to replace path prefix `/var/run/s3-bucket` with object storage downloads

Configuration could look something like:

```
path-remap:
    "/var/run/s3-bucket":
         driver: GenericS3
         base: s3://my-bucket/data
```
